### ISSUE TITLE
我使用sealoader加载模块之后，页面控制台输出找不到seajs-myUntils.js和seajs-httpClientConfig.js

### ISSUE THREAD

**Issue by JsonID** [328080339/JsLibs#2]
页面控制台输出找不到seajs-myUntils.js和seajs-httpClientConfig.js并且是在根目录下
报错具体信息：
sea.js:1 GET file:///seajs-myUtils.js net::ERR_FILE_NOT_FOUND
sea.js:1 GET file:///seajs-httpClientConfig.js net::ERR_FILE_NOT_FOUND
sea.js:1 Uncaught Error: module was broken: file:///seajs-httpClientConfig.js
搞了一上午，头大，
求解

**Comment by aweiu** [comment]
在你的根目录下创建:seajs-myUntils.js和seajs-httpClient.js
https://github.com/aweiu/JsLibs/wiki/Home(%E5%BF%85%E8%AF%BB)#seajs-myuntilsjs%E5%92%8Cseajs-httpclientconfigjs%E6%8A%A5%E9%94%99%E5%A4%84%E7%90%86

**Comment by JsonID** [comment]
问题解决了
Thank you  大牛
