### ISSUE TITLE
seajs-tablePage这个插件不支持跨域请求，换成jQuery的ajax方式就可以了

### ISSUE THREAD

**Issue by JsonID** [328080339/JsLibs#3]
服务器端已经设置了header接受所有的请求，但是seajs-tablePage这个插件还是不能进行跨域请求，换成jQuery的ajax方式就可以进行跨域了，希望能做改进，谢谢

**Comment by aweiu** [comment]
服务端如果在header中设置了Access-Control-Allow-Origin 应该是可以跨域的
你可以尝试在你的开发环境中跨域请求http://awei.oss-cn-shenzhen.aliyuncs.com/tablePage.txt
